### ISSUE TITLE
Error running scdc using singularity

### ISSUE THREAD

**Issue by tkamth** [bedapub/bescape#2]
Singularity client gets loaded but somehow the sclient.execute from spython appears to be missing.  (bescape/_deconv.py ) 

>>> import os
>>> from bescape import Bescape
>>> 
>>> # singularity
... deconv = Bescape(service='singularity', docker_image='bedapub/bescape:0.5', path_singularity=None)
singularity pull --name bescape.sif docker://bedapub/bescape:0.5
bescape.sif
Singularity client loaded
Singularity container loaded:  None
>>> wd = os.getcwd()
>>> dir_annot = wd + '/datasets/scdc/gep/'
>>> dir_input = wd + '/datasets/scdc/input'
>>> dir_output = wd + '/datasets/scdc/output'
>>> 
>>> deconv.deconvolute_sc(dir_annot=dir_annot, 
...                       dir_input=dir_input,
...                       dir_output=dir_output, 
...                       method='scdc', 
...                       celltype_var='cluster', 
...                       celltype_sel=["alpha","beta","delta","gamma","acinar","ductal"], 
...                       sample_var='sample')
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "~/.conda/envs/besca_2/lib/python3.6/site-packages/bescape/_deconv.py", line 153, in deconvolute_sc
    self.sclient.execute(cmd, bind=param_bind)
AttributeError: 'str' object has no attribute 'execute'
>>> deconv.sclient.
deconv.sclient.capitalize(    deconv.sclient.find(          deconv.sclient.isdigit(       deconv.sclient.isupper(       deconv.sclient.replace(       deconv.sclient.split(         deconv.sclient.upper(
deconv.sclient.casefold(      deconv.sclient.format(        deconv.sclient.isidentifier(  deconv.sclient.join(          deconv.sclient.rfind(         deconv.sclient.splitlines(    deconv.sclient.zfill(
deconv.sclient.center(        deconv.sclient.format_map(    deconv.sclient.islower(       deconv.sclient.ljust(         deconv.sclient.rindex(        deconv.sclient.startswith(    
deconv.sclient.count(         deconv.sclient.index(         deconv.sclient.isnumeric(     deconv.sclient.lower(         deconv.sclient.rjust(         deconv.sclient.strip(         
deconv.sclient.encode(        deconv.sclient.isalnum(       deconv.sclient.isprintable(   deconv.sclient.lstrip(        deconv.sclient.rpartition(    deconv.sclient.swapcase(      
deconv.sclient.endswith(      deconv.sclient.isalpha(       deconv.sclient.isspace(       deconv.sclient.maketrans(     deconv.sclient.rsplit(        deconv.sclient.title(         
deconv.sclient.expandtabs(    deconv.sclient.isdecimal(     deconv.sclient.istitle(       deconv.sclient.partition(     deconv.sclient.rstrip(        deconv.sclient.translate(

**Comment by tkamth** [comment]
Version issue, update notebook bescape_tutorial.ipynb
