### ISSUE TITLE
issues with singularity

### ISSUE THREAD

**Issue by JAttig** [bedapub/bescape#6]
[complete error and traceback at the end]

I tried to run through bescape with the Singularity set-up and failed. 
The first time, it downloads 'bescape/sif' and appears to work fine

```
# singularity
deconv = Bescape(service='singularity', docker_image='bedapub/bescape:0.5', path_singularity='bescape.sif')
# singularity
deconv = Bescape(service='singularity', docker_image='bedapub/bescape:0.5', path_singularity='bescape.sif')
bescape.sif
Singularity client loaded
Singularity container loaded:  bescape.sif
```

but then when accessing Music, the set-up lacks the library...

ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Error in library(MuSiC) : there is no package called ‘MuSiC’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted

complete error tb:
```
deconv.deconvolute_sc(dir_annot= dir_annot, 
                      dir_input= dir_input,
                      dir_output= dir_output, 
                      method='music')

ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Error in library(MuSiC) : there is no package called ‘MuSiC’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted
ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/pstore/apps/bin/lib/libogrt.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Traceback (most recent call last):
  File "/app/musicpy.py", line 39, in <module>
    pred = music(gep=file_annot, bulk_rna=dir_input)
  File "/app/musicpy.py", line 28, in music
    out = pd.read_csv('temp.txt', sep='\t', header=0, index_col=0)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File temp.txt does not exist: 'temp.txt'


CalledProcessError: Command '['singularity', '--quiet', 'exec', '--bind', '/pstore/data/biomics_clin/ONC/ReverseTranslation/celldeconv/Q12021/input/testrun/:/app/input', '--bind', '/pstore/data/biomics_clin/ONC/ReverseTranslation/celldeconv/Q12021/output/iteration1/:/app/output', '--bind', '/pstore/data/biomics_clin/ONC/ReverseTranslation/celldeconv/Q12021/GEPs/:/app/gep', 'bescape.sif', 'python3', '/app/musicpy.py']' returned non-zero exit status 1.
```

**Comment by JAttig** [comment]
[update] If I try to run SCDC with the same singulatiry image, I get
`ERROR /app/input does not exist on host.`

**Comment by mirophan** [comment]
For Music: `\FileNotFoundError: [Errno 2] File temp.txt does not exist: 'temp.txt'`  is probably because the input data could not be loaded. 

I would look into how singularity is called:
https://github.com/bedapub/bescape/blob/ead6d5005eedf8e846c03f32caa0d55c7ea42b0a/bescape/_deconv.py#L127

The documentation for the API used is here:
https://singularityhub.github.io/singularity-cli/commands-images

**Comment by JAttig** [comment]
Hi Miro thx for the input. it turns out I had the wrong singularity version with 'docker_image='bedapub/bescape:0.5' instead of 'bedapub/bescape:latest'
bw. Jan
